require "jarod.pluggins"
require "jarod.keybinds"
require "jarod.options"
require "jarod.colors"
require "jarod.cmp"
require "jarod.treesitter"
require "jarod.telescope"
require "jarod.whichkey"
require "jarod.nvimtree"
require "jarod.toggleterm"
require "jarod.lualine"
require "jarod.lsp"
require "colorizer".setup()
require "jarod.autopairs"
require "jarod.gitsigns"
require "jarod.autocommands"

