require "jarod.pluggins"
require "jarod.keybinds"
require "jarod.options"
require "jarod.colors"
require "jarod.cmp"
require "jarod.treesitter"
require "jarod.telescope"
require "jarod.whichkey"

require "lsp"
